GET http://localhost:3000/usuario

###
GET http://localhost:3000/usuario/1

###
POST http://localhost:3000/usuario
content-type: application/json

{
    "nome": "Bruno Wellington",
    "email": "bruno@gmail.com",
    "senha": "123456789"
}
###
POST http://localhost:3000/usuario
content-type: application/json

{
    "nome": "Patricia Kauanny",
    "email": "Patricia@gmail.com",
    "senha": "123456789"
}

###
PATCH http://localhost:3000/usuario/1
content-type: application/json

{
    "nome": "Bruno Wellington Lima Carvalho",
    "email": "brunodev@gmail.com",
    "senha": "888888"
}

###
DELETE  http://localhost:3000/usuario/2

